# Generated by Django 4.0.5 on 2022-06-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='cateory',
            new_name='category',
        ),
    ]
