# Generated by Django 4.0.5 on 2022-06-28 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_comments_comment_alter_comment_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_added',
            new_name='created_at',
        ),
    ]
