# Generated by Django 4.0.5 on 2022-06-30 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='github',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
